language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
solution: PredictiveModelling.sln

script:
 - dotnet restore
 - dotnet test ./PredictiveModellingTest/PredictiveModellingTest.csproj
