language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
solution: PredictiveModelling.sln

env:

script:
   - dotnet restore
   - dotnet test ./PredictiveModellingTest/PredictiveModellingTest.csproj /p:CollectCoverage=true

before_script:
   - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
   - chmod +x ./PredictiveModellingTest/cc-test-reporter
   - ./cc-test-reporter before-build

script:
   - dotnet restore
   - dotnet test ./PredictiveModellingTest/PredictiveModellingTest.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./PredictiveModellingTest/cobertura.xml